# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acdoscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from acceptorscreen import Ui_acceptorwindow
from donorscreen import Ui_donorwindow


class Ui_acdowindow(object):

    def nextacc(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_acceptorwindow()
        self.ui.setupUi (self.window)
        #profilewindow.hide() 
        self.window.show()
    
    def nextdon(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_donorwindow()
        self.ui.setupUi (self.window)
        #profilewindow.hide() 
        self.window.show()

    def backp(self):
        from profilescreen import Ui_profilewindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_profilewindow()
        self.ui.setupUi (self.window)
        #acdowindow.hide()
        self.window.show()

    def setupUi(self, acdowindow):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        acdowindow.setWindowIcon(icon)
        acdowindow.setObjectName("acdowindow")
        acdowindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(24)
        acdowindow.setFont(font)
        self.ExitAcDo = QtWidgets.QPushButton(acdowindow)
        self.ExitAcDo.setGeometry(QtCore.QRect(290, 680, 121, 41))
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(16)
        self.ExitAcDo.setFont(font)
        self.ExitAcDo.setObjectName("ExitAcDo")
        self.label_3AcDo = QtWidgets.QLabel(acdowindow)
        self.label_3AcDo.setGeometry(QtCore.QRect(870, 420, 91, 111))
        self.label_3AcDo.setText("")
        self.label_3AcDo.setPixmap(QtGui.QPixmap("../1.png"))
        self.label_3AcDo.setObjectName("label_3AcDo")
        self.labelAcDo = QtWidgets.QLabel(acdowindow)
        self.labelAcDo.setGeometry(QtCore.QRect(700, 230, 221, 81))
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelAcDo.setFont(font)
        self.labelAcDo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelAcDo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAcDo.setObjectName("labelAcDo")
        self.pushButtonAcDo = QtWidgets.QPushButton(acdowindow)
        self.pushButtonAcDo.setGeometry(QtCore.QRect(610, 360, 191, 51))
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(28)
        self.pushButtonAcDo.setFont(font)
        self.pushButtonAcDo.setObjectName("pushButtonAcDo")
        self.pushButtonAcDo.clicked.connect(self.nextacc)
        self.pushButton_2 = QtWidgets.QPushButton(acdowindow)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 360, 161, 51))
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(28)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.nextdon)
        self.label_4AcDo = QtWidgets.QLabel(acdowindow)
        self.label_4AcDo.setGeometry(QtCore.QRect(650, 440, 91, 61))
        self.label_4AcDo.setText("")
        self.label_4AcDo.setPixmap(QtGui.QPixmap("../2.png"))
        self.label_4AcDo.setObjectName("label_4AcDo")
        self.BackAcDo = QtWidgets.QPushButton(acdowindow)
        self.BackAcDo.setGeometry(QtCore.QRect(40, 40, 71, 41))
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(16)
        self.BackAcDo.setFont(font)
        self.BackAcDo.setAutoFillBackground(True)
        self.BackAcDo.setObjectName("BackAcDo")
        self.BackAcDo.clicked.connect(self.backp)

        self.retranslateUi(acdowindow)
        self.ExitAcDo.clicked.connect(acdowindow.close)
        self.pushButton_2.clicked.connect(acdowindow.hide)
        self.pushButtonAcDo.clicked.connect(acdowindow.hide)
        self.BackAcDo.clicked.connect(acdowindow.hide)
        QtCore.QMetaObject.connectSlotsByName(acdowindow)

    def retranslateUi(self, acdowindow):
        _translate = QtCore.QCoreApplication.translate
        acdowindow.setWindowTitle(_translate("acdowindow", "Acceptor Or Donor"))
        self.ExitAcDo.setText(_translate("acdowindow", "Exit"))
        self.labelAcDo.setText(_translate("acdowindow", "YOU ARE A ...."))
        self.pushButtonAcDo.setText(_translate("acdowindow", "Acceptor"))
        self.pushButton_2.setText(_translate("acdowindow", "Donor"))
        self.BackAcDo.setText(_translate("acdowindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    acdowindow = QtWidgets.QWidget()
    ui = Ui_acdowindow()
    ui.setupUi(acdowindow)
    #Ui_profilewindow.hide() 
    acdowindow.show()
    sys.exit(app.exec_())
