# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_finalwindow(object):
    
    def setupUi(self, finalwindow):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        finalwindow.setWindowIcon(icon)
        finalwindow.setObjectName("finalwindow")
        finalwindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("CentSchbkCyrill BT")
        font.setPointSize(24)
        finalwindow.setFont(font)
        self.EnterdetailsFinal = QtWidgets.QLabel(finalwindow)
        self.EnterdetailsFinal.setGeometry(QtCore.QRect(280, 170, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.EnterdetailsFinal.setFont(font)
        self.EnterdetailsFinal.setWordWrap(True)
        self.EnterdetailsFinal.setObjectName("EnterdetailsFinal")
        self.ExitFinal = QtWidgets.QPushButton(finalwindow)
        self.ExitFinal.setGeometry(QtCore.QRect(710, 650, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.ExitFinal.setFont(font)
        self.ExitFinal.setObjectName("ExitFinal")
        self.label = QtWidgets.QLabel(finalwindow)
        self.label.setGeometry(QtCore.QRect(1090, 110, 281, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../HOSP.png"))
        self.label.setObjectName("label")
        self.groupBoxFinal = QtWidgets.QGroupBox(finalwindow)
        self.groupBoxFinal.setGeometry(QtCore.QRect(570, 290, 421, 251))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBoxFinal.setFont(font)
        self.groupBoxFinal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBoxFinal.setObjectName("groupBoxFinal")
        self.hospnameFinalLabel_3 = QtWidgets.QLabel(self.groupBoxFinal)
        self.hospnameFinalLabel_3.setGeometry(QtCore.QRect(20, 50, 171, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hospnameFinalLabel_3.setFont(font)
        self.hospnameFinalLabel_3.setObjectName("hospnameFinalLabel_3")
        self.FinalplainTextEdit = QtWidgets.QPlainTextEdit(self.groupBoxFinal)
        self.FinalplainTextEdit.setGeometry(QtCore.QRect(200, 50, 201, 61))
        self.FinalplainTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FinalplainTextEdit.setReadOnly(True)
        self.FinalplainTextEdit.setObjectName("FinalplainTextEdit")
        self.phonenoFinalLabel_4 = QtWidgets.QLabel(self.groupBoxFinal)
        self.phonenoFinalLabel_4.setGeometry(QtCore.QRect(20, 150, 181, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.phonenoFinalLabel_4.setFont(font)
        self.phonenoFinalLabel_4.setObjectName("phonenoFinalLabel_4")
        self.FinalplainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBoxFinal)
        self.FinalplainTextEdit_2.setGeometry(QtCore.QRect(200, 150, 201, 31))
        self.FinalplainTextEdit_2.setMinimumSize(QtCore.QSize(201, 31))
        self.FinalplainTextEdit_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FinalplainTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.FinalplainTextEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.FinalplainTextEdit_2.setReadOnly(True)
        self.FinalplainTextEdit_2.setObjectName("FinalplainTextEdit_2")

        self.retranslateUi(finalwindow)
        self.ExitFinal.clicked.connect(finalwindow.close)
        QtCore.QMetaObject.connectSlotsByName(finalwindow)

    def retranslateUi(self, finalwindow):
        _translate = QtCore.QCoreApplication.translate
        finalwindow.setWindowTitle(_translate("finalwindow", "Hospital Details"))
        self.EnterdetailsFinal.setText(_translate("finalwindow", "Details: "))
        self.ExitFinal.setText(_translate("finalwindow", "Exit"))
        self.groupBoxFinal.setTitle(_translate("finalwindow", "Hospital Details"))
        self.hospnameFinalLabel_3.setText(_translate("finalwindow", "Hospital Name: "))
        self.phonenoFinalLabel_4.setText(_translate("finalwindow", "Phone Number: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    finalwindow = QtWidgets.QWidget()
    ui = Ui_finalwindow()
    ui.setupUi(finalwindow)
    finalwindow.show()
    sys.exit(app.exec_())
